# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "r1" do |r1|
    r1.vm.box = "debian/bullseye64"
    r1.vm.hostname = "r1"
    r1.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false
    r1.vm.network "private_network", virtualbox__intnet: "intnet-2", auto_config: false
    r1.vm.network "private_network", virtualbox__intnet: "intnet-3", auto_config: false
    r1.vm.synced_folder "r1/", "/rtr", owner: "root", group: "root", id: "vagrant-root", extra: "dmode=777,fmode=777"
    r1.vm.provider "virtualbox" do |vbox|
      vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
      vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
      vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
      vbox.memory = "1024"
      vbox.cpus = 1
      vbox.name = "bp-master"
    end
  end

  config.vm.define "r2" do |r2|
    r2.vm.box = "debian/bullseye64"
    r2.vm.hostname = "r2"
    r2.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false
    r2.vm.network "private_network", virtualbox__intnet: "intnet-2", auto_config: false
    r2.vm.network "private_network", virtualbox__intnet: "intnet-3", auto_config: false
    #r2.vm.synced_folder "./r2", "/rtr", create: true, owner: "root", group: "root", type: "rsync"
    r2.vm.provider "virtualbox" do |vbox|
      vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
      vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
      vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
      vbox.memory = "1024"
      vbox.cpus = 1
      vbox.name = "bp-worker"
      #vbox.gui = true
    end
  end

  config.vm.define "r5" do |r5|
    r5.vm.box = "debian/bullseye64"
    r5.vm.hostname = "r5"
    r5.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false
    r5.vm.network "private_network", virtualbox__intnet: "intnet-3", auto_config: false
    #r5.vm.synced_folder "r5/", "/rtr", create: true, owner: "root", group: "root", type: "rsync"
    r5.vm.provider "virtualbox" do |vbox|
      vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
      vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
      vbox.memory = "1024"
      vbox.cpus = 1
      vbox.name = "bp-client"
    end
  end

end
